global:
  imageRegistry: docker.io/noletengine
  imagePullPolicy: IfNotPresent

frontend:
  replicaCount: 1
  image:
    name: simple-frontend
    tag: "latest"        # default, workflow injects SHA at deploy
    pullPolicy: ""
  service:
    type: ClusterIP
    port: 80
    targetPort: 80

backendV1:
  replicaCount: 1
  image:
    name: simple-backend-v1
    tag: "latest"        # default, workflow injects SHA at deploy
    pullPolicy: ""
  service:
    type: ClusterIP
    port: 5000
    targetPort: 5000

backendV2:
  replicaCount: 1
  image:
    name: simple-backend-v2
    tag: "latest"        # default, workflow injects SHA at deploy
    pullPolicy: ""
  service:
    type: ClusterIP
    port: 5001
    targetPort: 5000     # v2 still listens inside container on 5000

istio:
  enabled: true
  gateway:
    hosts:
      - "*"
