global:
  imageRegistry: docker.io/noletengine
  imageTag: latest
  imagePullPolicy: IfNotPresent

frontend:
  replicaCount: 1
  image:
    name: simple-frontend
    tag: ""
    pullPolicy: ""
  service:
    type: ClusterIP
    port: 80
    targetPort: 80

backend:
  replicaCount: 1
  image:
    name: simple-backend
    tag: ""
    pullPolicy: ""
  service:
    type: ClusterIP
    port: 5000
    targetPort: 5000
