global:
  imageRegistry: docker.io/noletengine
  imageTag: latest
  imagePullPolicy: IfNotPresent

frontend:
  replicaCount: 1
  image:
    name: simple-frontend   # use "name"
    tag: ""
    pullPolicy: ""
  service:
    type: NodePort
    port: 80
    targetPort: 80
    nodePort: 30080

backend:
  replicaCount: 1
  image:
    name: simple-backend    # use "name"
    tag: ""
    pullPolicy: ""
  service:
    type: ClusterIP
    port: 5000
    targetPort: 5000
