apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-v2
  labels:
    app: backend
    version: v2
spec:
  replicas: {{ .Values.backendV2.replicaCount }}
  selector:
    matchLabels:
      app: backend
      version: v2
  template:
    metadata:
      labels:
        app: backend
        version: v2
    spec:
      containers:
      - name: backend
        image: "{{ .Values.global.imageRegistry }}/{{ .Values.backendV2.image.name }}:{{ .Values.backendV2.image.tag | default .Values.global.imageTag }}"
        imagePullPolicy: {{ .Values.backendV2.image.pullPolicy | default .Values.global.imagePullPolicy }}
        ports:
        - containerPort: {{ .Values.backendV2.service.targetPort }}
