apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-v1
  labels:
    app: backend
    version: v1
spec:
  replicas: {{ .Values.backendV1.replicaCount }}
  selector:
    matchLabels:
      app: backend
      version: v1
  template:
    metadata:
      labels:
        app: backend
        version: v1
    spec:
      containers:
      - name: backend
        image: "{{ .Values.global.imageRegistry }}/{{ .Values.backendV1.image.name }}:{{ .Values.backendV1.image.tag | default .Values.global.imageTag }}"
        imagePullPolicy: {{ .Values.backendV1.image.pullPolicy | default .Values.global.imagePullPolicy }}
        ports:
        - containerPort: {{ .Values.backendV1.service.targetPort }}
