apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: "{{ .Values.global.imageRegistry }}/{{ .Values.frontend.image.name }}:{{ .Values.frontend.image.tag | default .Values.global.imageTag }}"
        imagePullPolicy: {{ .Values.frontend.image.pullPolicy | default .Values.global.imagePullPolicy }}
        ports:
        - containerPort: {{ .Values.frontend.service.targetPort }}
        command: ["sh", "-c", "echo '<h1>Simple Frontend</h1><p>Go to /api for backend canary test.</p>' > index.html && python3 -m http.server {{ .Values.frontend.service.targetPort }}"]
