apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-v2
  labels:
    app: backend
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
      version: v2
  template:
    metadata:
      labels:
        app: backend
        version: v2
    spec:
      containers:
      - name: backend
        image: "{{ .Values.global.imageRegistry }}/{{ .Values.backend.image.repository }}:canary"
        imagePullPolicy: {{ .Values.backend.image.pullPolicy | default .Values.global.imagePullPolicy }}
        ports:
        - containerPort: {{ .Values.backend.service.targetPort }}
        command: ["sh", "-c", "echo 'Hello from Backend v2 (canary)' > index.html && python3 -m http.server {{ .Values.backend.service.targetPort }}"]
