apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: simple-app-gateway
  namespace: staging
spec:
  selector:
    istio: ingressgateway   # use your Istio ingress gateway labels
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
