apiVersion: v1
kind: Service
metadata:
  name: backend-v2
  labels:
    app: backend
    version: v2
spec:
  type: {{ .Values.backendV2.service.type }}
  ports:
    - port: {{ .Values.backendV2.service.port }}
      targetPort: {{ .Values.backendV2.service.targetPort }}
  selector:
    app: backend
    version: v2
