apiVersion: v1
kind: Service
metadata:
  name: backend-v1
  labels:
    app: backend
    version: v1
spec:
  selector:
    app: backend
    version: v1
  ports:
    - port: {{ .Values.backendV1.service.port }}
      targetPort: {{ .Values.backendV1.service.targetPort }}
