apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: simple-app
spec:
  hosts:
  - "*"
  gateways:
  - simple-app-gateway
  http:
  - match:
    - uri:
        prefix: /api
    fault:
      delay:
        fixedDelay: 2s
        percent: 20
      abort:
        httpStatus: 503
        percent: 5
    route:
    - destination:
        host: backend
        subset: v1
        port:
          number: 5000
      weight: 80
    - destination:
        host: backend
        subset: v2
        port:
          number: 5000
      weight: 20
  - route:
    - destination:
        host: frontend
        port:
          number: 80
