apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: simple-app
  namespace: staging
spec:
  hosts:
  - "*"
  gateways:
  - simple-app-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: frontend
        port:
          number: 80
