name: CI/CD Deploy Simple Istio App

on:
  push:
    branches: ["main"]

jobs:
  build-and-push:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Frontend
        run: |
          IMAGE=docker.io/${{ secrets.DOCKERHUB_USERNAME }}/simple-frontend:${GITHUB_SHA}
          docker build -t $IMAGE ./frontend
          docker push $IMAGE
          echo "FRONTEND_IMAGE=$IMAGE" >> $GITHUB_ENV

      - name: Build & Push Backend v1
        run: |
          IMAGE=docker.io/${{ secrets.DOCKERHUB_USERNAME }}/simple-backend-v1:${GITHUB_SHA}
          docker build -t $IMAGE ./backend-v1
          docker push $IMAGE
          echo "BACKEND_V1_IMAGE=$IMAGE" >> $GITHUB_ENV

      - name: Build & Push Backend v2
        run: |
          IMAGE=docker.io/${{ secrets.DOCKERHUB_USERNAME }}/simple-backend-v2:${GITHUB_SHA}
          docker build -t $IMAGE ./backend-v2
          docker push $IMAGE
          echo "BACKEND_V2_IMAGE=$IMAGE" >> $GITHUB_ENV

      - name: Update Helm values.yaml
        run: |
          sed -i "s|simple-frontend:.*|simple-frontend:${GITHUB_SHA}|" charts/simple-app/values.yaml
          sed -i "s|simple-backend-v1:.*|simple-backend-v1:${GITHUB_SHA}|" charts/simple-app/values.yaml
          sed -i "s|simple-backend-v2:.*|simple-backend-v2:${GITHUB_SHA}|" charts/simple-app/values.yaml

      - name: Commit and push updated values.yaml
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add charts/simple-app/values.yaml
          git commit -m "Update images to $GITHUB_SHA"
          git push

